# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy
      env:
        ConnectionStrings__PostgreSQL: ${{ secrets.POSTGRESQL_CONNECTION_STRING }}
        Telegram__Token: ${{ secrets.TELEGRAM_TOKEN }}
        Telegram__IdAdmin: ${{ secrets.TELEGRAM_ID_ADMIN }}
        Jwt__Issure: ${{ secrets.JWT_ISSURE }}
        Jwt__Audience: ${{ secrets.JWT_AUDIENCE }}
        Jwt__Expires: ${{ secrets.JWT_EXPIRES }}
        Jwt__SecretKey: ${{ secrets.JWT_SECRET_KEY }}
      run: |
        echo "Deploying application..."
#jobs:
  #build:

    #runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v4
    #- name: Setup .NET
     # uses: actions/setup-dotnet@v4
      #with:
        #dotnet-version: 8.0.x
    #- name: Restore dependencies
      #run: dotnet restore
    #- name: Build
      #run: dotnet build --no-restore
    #- name: Test
      #run: dotnet test --no-build --verbosity normal
